[font]
size = 14

[general]
import = ["~/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_moon.toml"]

[mouse]
hide_when_typing = true

[terminal.shell]
program = "tmux"

[window]
startup_mode = "Maximized"
