[custom.cpp]
command = "gcc -dumpfullversion"
symbol = "î˜"
detect_extensions = ["cpp", "cc", "hpp", "cxx"]
style = "bold cyan"
format = "via [$symbol v$output-gcc]($style) "

[cmake]
detect_extensions = ["cmake"]

[custom.vim]
command = "nvim -v | head -1 | cut -d- -f1"
symbol = "î˜«"
detect_extensions = ["vim"]
style = "bold green"
format = "via [$symbol $output]($style) "

[lua]
disabled = true

[custom.lua]
command = "nvim -v | head -1 | cut -d- -f1"
symbol = "ğŸŒ™"
detect_extensions = ["lua"]
style = "bold blue"
format = "via [$symbol $output]($style) "
