[custom.cpp]
command = "gcc -dumpversion"
symbol = "î˜"
detect_extensions = ["cpp", "cc", "hpp", "cxx"]
style = "bold cyan"
format = "via [$symbol v$output]($style) "

[cmake]
detect_extensions = ["cmake"]
